language: php

php:
  - 7.1
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly

before_install:
 - phpenv config-rm xdebug.ini

install:
 - composer global require satooshi/php-coveralls sllh/composer-lint codeclimate/php-test-reporter --prefer-dist --no-interaction
 - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

before_script:
 - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - composer validate
 - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
 - coveralls -v
 - test-reporter
